### ISSUE TITLE
Create a GitHub Release

### ISSUE THREAD

**Issue by favoyang** [johnsoncodehk/unity-asset-inspector#2]
Hi @johnsoncodehk,

Could you please create a [GitHub release](https://github.com/johnsoncodehk/unity-asset-inspector/releases) `v1.0.0`? I submitted the package to [OpenUPM](https://openupm.com/packages/com.johnsoncodehk.unity-asset-inspector/) a public upm registry which build package based on git tags automatically. It requires at least a GitHub release (a git tag with name vx.y.z) to make it work.

**Comment by johnsoncodehk** [comment]
Thanks for your work!
I already release ```v1.0.0```, but I'm not sure if it working.

**Comment by favoyang** [comment]
There's a weird thing that the OpenUPM build pipelines fetched the tag name `1.0.0`, but the real tag name is `v1.0.0` (with prefix v). It's the first time I meet the issue. I didn't find any issue in my code so far, I suspect the only case is that a tag `1.0.0` was created, lately get deleted and replaced with tag `v1.1.0` (in your side), during the processing of build pipelines.

Anyway, I correct the data manually, now the[ version 1.0.0](https://openupm.com/packages/com.johnsoncodehk.unity-asset-inspector/) is bundled correctly. 

![image](https://user-images.githubusercontent.com/125390/71539403-8e63b400-2976-11ea-9bbe-cd7daccece75.png)

Thanks for the efforts!

**Comment by johnsoncodehk** [comment]
The ```1.0.0``` tag seem exist before I release ```v1.0.0```, it may be capture from package.json?
Anyway thanks for your work :)
